databases:
  - name: mysitedb
    plan: free
    databaseName: ecommerce
    user: ecommerce

services:
  - type: web
    plan: free
    name: ecommerce
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ecommerce.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    staticPublishPath: staticfiles
